### PR TITLE
Update community_rules.md

### PR DESCRIPTION
**Pull request by AestheticSenpai**
New additions

### CODE REVIEW

**Review by cryptozeny — CHANGES_REQUESTED** [review]
it seems all good, but too much i guess? i do not want more than 12 rules IMO :sweat_smile:

**Comment by cryptozeny** [comment]
but why closed? :sweat:

**Comment by cryptozeny** [comment]
still you can change the PR, but anyway no problem

**Comment by AestheticSenpai** [comment]
idk how to do this lol

**Pull request closed without merging**
